### ISSUE TITLE
PDF creation button has problem with Arabic script

### ISSUE THREAD

**Issue by pverkind** [sohailmerchant/kitab-corpus-metadata#18]
Arabic letters are represented by ☒☒☒☒☒☒☒.
Also, the table spills over the border of the page. 
If we cannot solve this bug, we should probably remove this button. People can download the Excel version and save as PDF from there.

**Comment by pverkind** [comment]
I managed to solve this partly in commit #2114dbf: the pdf now correctly displays Arabic letters. 
However, the PDF output still looks bad: half of the table is cut off, and the text of some of the cells is jumbled

**Comment by pverkind** [comment]
These links proved useful: 
https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
https://datatables.net/reference/button/pdfHtml5

**Comment by sohailmerchant** [comment]
Performance was a real issue so I have removed this feature.  I don't think it was most wanted as such.
