### ISSUE TITLE
Make Arabic version default

### ISSUE THREAD

**Issue by pverkind** [sohailmerchant/kitab-corpus-metadata#21]
Sohail, do you mind making the Arabic version default (i.e., rename the arabic-version.html file to index.html)? Sarah asked me to write a blog about the new Arabic-language metadata app, so it would be nice if by the time that is published, it has become the default.

**Comment by sohailmerchant** [comment]
@pverkind, you mean that there shouldn't be any index.html page? and our default page to app should be arabic version without srt file etc... if yes,  we will need to take approval from Sarah.

**Comment by pverkind** [comment]
Hi @sohailmerchant, I mean that the Arabic version without srt files should be named index.html, so that when you go to https://kitab-corpus-metadata.azurewebsites.net/, you get to the Arabic version without srt files.

**Comment by sohailmerchant** [comment]
@pverkind, I will do that after we have merge all the changes.
